# config/database.yml
doctrine:
    dbal:
        driver:   'mysql'
        host:     'localhost'
        dbname:   'dailylog'
        user:     'dailylogUser'
        password: 'dailylogK3ys'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        